### ISSUE TITLE
React sample keeps redirecting after login

### ISSUE THREAD

**Issue by vinnybrown** [Azure/ms-rest-browserauth#21]
Steps to reproduce:

1. Sign out of any/all browser instances of the azure portal
2. Start the React sample
3. Click Login
**Expected results**:
=> I go through the SSO process (choose an account, go to my company login page then get redirected back to the main sample page being authenticated.
**Actual results**:
=> I go through the SSO process, get redirected back to the main sample page, but then get stuck in a redirect loop where I have to repeat the authentication process over and over.

**Comment by vinnybrown** [comment]
I've got a bit more info on this. It appears the issue is that _supportsLocalStorage always returns false. Still trying to dig into why that is, but hopefully that points to a solution.

**Comment by seekerlee** [comment]
I use the vanilla version, keeps redirecting too.

**Comment by ramya-rao-a** [comment]
@HarshaNalluru, Any ideas here based on your investigations done as part of #28 ?

**Comment by HarshaNalluru** [comment]
I couldn't repro the issue. The older react app sample has outdated dependencies, I'll soon be updating the sample to get it to a working condition.

@vinnybrown, Can you try out the newer sample [authentication-with-popup](https://github.com/Azure/ms-rest-browserauth/tree/master/samples/authentication-with-popup) which is meant for the authentication with popup.
https://github.com/Azure/ms-rest-browserauth/blob/8f4a086253bb36cd50faf727ed8b7cd08fb9ff4f/samples/authentication-with-popup/src/App.js#L28-L31
If you want to disable the popup and rely on the redirect from the above react app sample, update the sample as follows
- remove `popup: true` and 
- add the `tenant: tenantId`.

Then, edit `constants.js` file with `clientId` and `tenantId`, run `npm install` to install the dependencies and `npm start` to start the react app.
This would not get stuck in the redirect loop and should work as expected.

**Comment by aditya-baskar** [comment]
> I use the vanilla version, keeps redirecting too.

I am facing the same issue. Is there any solution?

**Comment by ramya-rao-a** [comment]
@aditya-baskar Did you try the suggestion from @HarshaNalluru above?

**Comment by asad1751** [comment]
I am facing a similar problem but only on my VM. The app works fine when I run it on my personal laptop, but when I run the same on my VM, the browser keeps redirecting to the login page. I think the issue might be with the finalizeLogin() method, because even if the authManager.login() method is not called, I still get redirected to the SSO. If I set popup: true, it does open a popup but it also redirects the page to login.

**Comment by HarshaNalluru** [comment]
@asad1715 Can you provide us info on how your VM environment looks like to give us a way to repro your problem?

@sadasant @maorleger Have you guys seen such redirect forever loop?

**Comment by sadasant** [comment]
@asad1751 I’m curious if this help:

1. Load the website hosted in your VM. Before login through popup or redirect, open the browser console, go to application memory and make sure to remove all of the local memory associated with this site, anything cached.
2. Once all is clean on your website, go to https://login.microsoftonline.com/common/oauth2/deviceauth , open the browser console and again, clear all of the local cache for that site.
3. Once both places have nothing locally cached, try to log-in from your site hosted in your VM.

Does that help?

Please also try the same on a new Incognito Mode session of your browser of preference.

In case you’re using the latest version of Chrome, if you’re on incognito, ensure that third party cookies are enabled.

**Comment by asad1751** [comment]
@HarshaNalluru I'm on an Azure VM using Windows 10 Enterprise for VDs.

@sadasant I tried that, it doesn't make much difference. Upon inspecting the local storage further, I saw that:
The first time that I visit the site (after clearing site data, it logs me in and I see that the local storage is populated with a bunch of adal login keys, the adal.idtoken is also filled (which may mean I am already logged in?) but it does not print out my available subscriptions in the console. Pressing the "Console.log available subscriptions" again, redirects to login and starts the infinite loop. If I restrict the print function just to the button to view changes in local storage, I see the error : "Token renewal operation failed due to timeout". It tries to renew the tokens even though I have them.
I debugged further and found that the finalizeLogin tries to renew tokens and fails due to timeout, therefore it never reaches the else block where I can get the credentials. Therefore, there is an infinite loop trying to get the credentials.

**Comment by sadasant** [comment]
@asad1751 thank you. Give us some days, we’ll get a VM working and we’ll figure out what’s going on.

**Comment by sadasant** [comment]
@asad1751 We’ll have an update for you by Wednesday 9th at most. Thank you for your patience.

**Comment by sadasant** [comment]
@asad1751 Hello! I finally found some time to set up a VM and so far I’m unable to reproduce this. Would you mind sharing the following information with us?

- If you go to your AAD app registration, and then to Authentication, do you have an entry for a Single Page Application redirect endpoint? And have you enabled the checkboxes used for implicit flow and hybrid flow?
- Would you mind providing us with the simplest code example and instructions to reproduce this issue?

**Comment by asad1751** [comment]
Yes, I've set up a SPA redirect and enabled implicit and hybrid flow.

I've tried all 3 samples and also included it in my own react app, problem seems to persist, I guess it is due to AAD or my subscription settings.

**Comment by sadasant** [comment]
@asad1751 Two more questions for you:

- Is this a personal account or a work account?
- Please ensure that cookies are enabled and try again from an incognito window: https://support.google.com/chrome/answer/95647 
- Can you try from another browser?
- Do you see any other error besides the redirection loop?

**Comment by sadasant** [comment]
@asad1751

Another question: Are you using ms-rest-browserauth to authenticate another Azure or Microsoft project?

At this point, we recommend you to try our Identity package: https://www.npmjs.com/package/@azure/identity We’re moving away from ms-rest-browserauth towards @azure/identity, so we’re dedicating most of our efforts into that new package. We will be able to more promptly follow up on your feedback there.

**Comment by xirzec** [comment]
Since there hasn't been any activity on this issue for over 90 days, I'm going to close. @asad1751 please let us know if you are still in need of assistance.
