### ISSUE TITLE
Relationship with msal.js

### ISSUE THREAD

**Issue by et1975** [Azure/ms-rest-browserauth#33]
Could someone elaborate on the criteria for choosing one over the other?
Looking at `ServiceClientCredentials` it should be implementable with a couple of lines using MSAL...

**Comment by daviwil** [comment]
This library is meant to be a wrapper for the older ADAL authentication library to adapt it to work with `ms-rest-js` in the browser.  You can easily do something similar with MSAL.js if you like, and I'd recommend that because MSAL.js 2.0 is actively developed and maintained.

Closing this issue for now, feel free to comment back if you have more questions.
